name: PR check

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: latest

      - uses: actions/checkout@v3

      - name: test
        run: pnpm i && pnpm lint && pnpm build
