name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: latest

      - uses: actions/checkout@v2

      - name: lint
        run: pnpm i && pnpm lint

      - name: build
        run: pnpm run build && touch docs/.vitepress/dist/.nojekyll && echo 'ics.liuly.moe' > docs/.vitepress/dist/CNAME

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: docs/.vitepress/dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
